In [33]:
import numpy as np

In [34]:
a1 = np.empty((2,2))
a2 = np.ones((4,2))
a3 = np.full((3,3), 7)

arr = np.array([[1,2,3],[4,5,6]])
a4 = np.zeros_like(arr)
a5 = np.ones_like(arr)

new_list = [1,2,3,4]
a6 = np.array(new_list)

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)


[[2.5e-323 1.5e-323]
 [9.9e-324 4.9e-324]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[1 2 3 4]


In [35]:
p2_1 = np.arange(10, 50)
p2_2 = np.arange(9).reshape(3,3)
p2_3 = np.eye(3)

rand30 = np.random.random(30)
p2_4 = rand30.mean()

arr10 = np.random.random((10,10))
p2_5_min = arr10.min()
p2_5_max = arr10.max()

p2_6 = np.zeros(10)
p2_6[4] = 1

arr = np.array([1,2,0,0,4,0])
p2_7 = arr[::-1]

p2_8 = np.ones((5,5))
p2_8[1:-1,1:-1] = 0

p2_9 = np.zeros((8,8))
p2_9[1::2, ::2] = 1
p2_9[::2, 1::2] = 1

print(p2_1)
print(p2_2)
print(p2_3)
print(p2_4)
print(p2_5_min, p2_5_max)
print(p2_6)
print(p2_7)
print(p2_8)
print(p2_9)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.4729796113238506
0.016126095893416847 0.9984279193877705
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [36]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

add_xy = x + y
sub_xy = x - y
mul_x = x * 3
square_x = x ** 2

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.column_stack((v, w))

try:
    bad_concat = np.concatenate((x, v))
    error_message = "No error"
except Exception as e:
    error_message = str(e)

print(add_xy)
print(sub_xy)
print(mul_x)
print(square_x)
print(dot_vw)
print(dot_xv)
print(dot_xy)
print(concat_xy_row)
print(concat_vw_col)
print(error_message)


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


We get an error because x is 2D (shape (2,2)) and v is 1D (shape (2,))so NumPy cannot concatenate them along the same axis

In [37]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

invA = np.linalg.inv(A)
identity_check = A @ invA

AB = A @ B
BA = B @ A

lhs = (A @ B).T
rhs = B.T @ A.T

print(identity_check)
print(AB)
print(BA)
print(lhs)
print(rhs)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [38]:
A_sys = np.array([
    [ 2, -3, 1],
    [ 1, -1, 2],
    [ 3,  1, -1]
])

B_sys = np.array([-1, -3, 9])

X1 = np.linalg.inv(A_sys) @ B_sys
X2 = np.linalg.solve(A_sys, B_sys)

print(X1)
print(X2)


[ 2.  1. -2.]
[ 2.  1. -2.]


In [32]:
import time
import numpy as np
import random

L1 = list(range(1_000_000))
L2 = list(range(1_000_000))

start = time.time()
L_add = [L1[i] + L2[i] for i in range(1_000_000)]
end = time.time()
t_add_list = end - start

A1 = np.arange(1_000_000)
A2 = np.arange(1_000_000)

start = time.time()
A_add = A1 + A2
end = time.time()
t_add_np = end - start

start = time.time()
L_mul = [L1[i] * L2[i] for i in range(1_000_000)]
end = time.time()
t_mul_list = end - start

start = time.time()
A_mul = A1 * A2
end = time.time()
t_mul_np = end - start

start = time.time()
dot_L = sum(L1[i] * L2[i] for i in range(1_000_000))
end = time.time()
t_dot_list = end - start

start = time.time()
dot_np = np.dot(A1, A2)
end = time.time()
t_dot_np = end - start

M1 = [[random.random() for _ in range(1000)] for _ in range(1000)]
M2 = [[random.random() for _ in range(1000)] for _ in range(1000)]

start = time.time()
M_result = [[sum(a*b for a,b in zip(r,c)) for c in zip(*M2)] for r in M1]
end = time.time()
t_matmul_list = end - start

A = np.random.rand(1000,1000)
B = np.random.rand(1000,1000)

start = time.time()
C = A @ B
end = time.time()
t_matmul_np = end - start

print(t_add_list)
print(t_add_np)
print(t_mul_list)
print(t_mul_np)
print(t_dot_list)
print(t_dot_np)
print(t_matmul_list)
print(t_matmul_np)


0.1115107536315918
0.0020492076873779297
0.1134958267211914
0.0022144317626953125
0.09999561309814453
0.0017316341400146484
170.71977639198303
0.056456565856933594
